In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
cd /content/drive/MyDrive/MCM/data

/content/drive/MyDrive/MCM/data

In [16]:
# Using readlines()
#wordle_answer.txt
# file1 = open('wordle_answer.txt', 'r')
file1 = open('all_five_letter.txt', 'r')
Lines = file1.readlines()
  
count = 0
# Strips the newline character‘
word_list = []
for line in Lines:
    count += 1
    word_list.append(line.strip())
file1.close()

In [17]:
len(word_list)

14855

In [14]:
import nltk
from tqdm import tqdm
word = word_list[0]
l = []
def count_l(l):
    dic = {}
    for i in l:
        if i not in dic:
            dic[i] = 1
        else:
            dic[i] += 1
    return dic

result = []
for word in tqdm(word_list):
    l = []
    for i in word_list[:]:
        l.append(nltk.edit_distance(word, i))
    result.append(count_l(l))
print(result)

  2%|▏         | 38/2309 [00:02<02:32, 14.91it/s]

KeyboardInterrupt: ignored

In [18]:
import nltk
from tqdm import tqdm
word = word_list[0]
l = []
def count_l(l):
    dic = {}
    for i in l:
        if i not in dic:
            dic[i] = 1
        else:
            dic[i] += 1
    return dic

result = []
for word in ['eerie']:
    l = []
    for i in word_list[:]:
        l.append(nltk.edit_distance(word, i))
    result.append(count_l(l))
print(result)

[{5: 9127, 4: 4659, 3: 987, 1: 2, 2: 79, 0: 1}]

In [11]:
ls

7_56.xlsx                         Problem_C_Data_Wordle.xlsx
all_five_letter.txt               roberta.large/
aoa.xlsx                          roberta.large.tar.gz
clean_data.xlsx                   roberta.large.tar.gz.1
data_label_kmeans_3.xlsx          temp_all.csv
new.xlsx                          timeseries_nlp.csv
nlp.csv                           WordDifficulty.csv
nlp_features_data.csv             wordle_answer.txt
Problem_C_Data_Wordle_label.xlsx

In [ ]:
list1,list2,list3,list4,list5 = [],[],[],[],[]
for i in result:

    if 1 in i:
        list1.append(i[1])
    else:
        list1.append(0)
    
    if 2 in i:
        list2.append(i[2])
    else:
        list2.append(0)
    
    if 3 in i:
        list3.append(i[3])
    else:
        list3.append(0)

    if 4 in i:
        list4.append(i[4])
    else:
        list4.append(0)

    if 5 in i:
        list5.append(i[5])
    else:
        list5.append(0)
    if max(i.keys())>5:
        print('here')

In [ ]:
d = {'Word': word_list,
        'short_1': list1,
        'short_2': list2,
        'short_3': list3,
        'short_4': list4,
        'short_5': list5,
    }
df = pd.DataFrame(data=d)
df.head()

    Word  short_1  short_2  short_3  short_4  short_5
0  aback        0       16      100      564     1628
1  abase        2       24      204      726     1352
2  abate        2       22      168      817     1299
3  abbey        0        6       71      796     1435
4  abbot        0        9       65      499     1735

In [ ]:
data = pd.read_csv('temp_all.csv').drop(columns='Unnamed: 0')   
data_merge = data.merge(df)
print(data_merge.head())
data_merge.info()
data_merge.to_csv('temp_all.csv')

         Date  Contest number   Word  Number of  reported results  \
0  2022-12-31             560  manly                        20380
1  2022-12-30             559  molar                        21204
2  2022-12-29             558  havoc                        20001
3  2022-12-28             557  impel                        20160
4  2022-12-26             555  judge                        20011

   Number in hard mode  1 try  2 tries  3 tries  4 tries  5 tries  ...  ng  \
0                 1899      0        2       17       37       29  ...   0
1                 1973      0        4       21       38       26  ...   0
2                 1919      0        2       16       38       30  ...   0
3                 1937      0        3       21       40       25  ...   0
4                 2043      0        2        8       16       26  ...   0

   qu  th  label2  label3  short_1  short_2  short_3  short_4  short_5
0   0   0     2.0     2.0        2       35      184      669     1418
1   0   0     2.0     2.0        2        8      137      702     1459
2   0   0     2.0     2.0        0        4       64      544     1696
3   0   0     2.0     2.0        0        4       77      524     1703
4   0   0     1.0     1.0        3       14       68      617     1606

[5 rows x 56 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 328 entries, 0 to 327
Data columns (total 56 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         328 non-null    object
 1   Contest number               328 non-null    int64
 2   Word                         328 non-null    object
 3   Number of  reported results  328 non-null    int64
 4   Number in hard mode          328 non-null    int64
 5   1 try                        328 non-null    int64
 6   2 tries                      328 non-null    int64
 7   3 tries                      328 non-null    int64
 8   4 tries                      328 non-null    int64
 9   5 tries                      328 non-null    int64
 10  6 tries                      328 non-null    int64
 11  7 or more tries (X)          328 non-null    int64
 12  word_format                  328 non-null    int64
 13  max_word_repetition          328 non-null    int64
 14  diff_score                   328 non-null    int64
 15  syllable                     328 non-null    int64
 16  brown_freq                   328 non-null    int64
 17  reuters_freq                 328 non-null    int64
 18  label                        328 non-null    int64
 19  Length                       328 non-null    int64
 20  Freq_HAL                     328 non-null    int64
 21  Log_Freq_HAL                 328 non-null    float64
 22  I_Mean_RT                    328 non-null    float64
 23  I_Zscore                     328 non-null    float64
 24  I_SD                         328 non-null    float64
 25  Obs                          328 non-null    float64
 26  I_Mean_Accuracy              328 non-null    float64
 27  f                            328 non-null    int64
 28  g                            328 non-null    int64
 29  j                            328 non-null    int64
 30  m                            328 non-null    int64
 31  p                            328 non-null    int64
 32  q                            328 non-null    int64
 33  v                            328 non-null    int64
 34  w                            328 non-null    int64
 35  x                            328 non-null    int64
 36  z                            328 non-null    int64
 37  oo                           328 non-null    int64
 38  ir                           328 non-null    int64
 39  ph                           328 non-null    int64
 40  ly                           328 non-null    int64
 41  ve                           328 non-null    int64
 42  wh                           328 non-null    int64
 43  sk                           328 non-null    int64
 44  ch                           328 non-null    int64
 45  ck                           328 non-null    int64
 46  ng                           328 non-null    int64
 47  qu                           328 non-null    int64
 48  th                           328 non-null    int64
 49  label2                       328 non-null    float64
 50  label3                       328 non-null    float64
 51  short_1                      328 non-null    int64
 52  short_2                      328 non-null    int64
 53  short_3                      328 non-null    int64
 54  short_4                      328 non-null    int64
 55  short_5                      328 non-null    int64
dtypes: float64(8), int64(46), object(2)
memory usage: 146.1+ KB